version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    restart: on-failure
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092

  kafka-chat:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - kafka
    restart: on-failure
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
    volumes:
      - .:/app
    working_dir: /app

  web:
    build: .
    command: uvicorn api.webapi:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - kafka
    restart: on-failure
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
    volumes:
      - .:/app
